version: "3.8"

services:
  postgres:
    image: postgres

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    depends_on:
      - postgres

  admin:
    build:
      context: .
      dockerfile: ./packages/admin/Dockerfile
